### ISSUE TITLE
Pair

### ISSUE THREAD

**Issue by eggind** [lflfm/powerBTremover#2]
Thanks for this powershell snippet. It is very helpful! Is there any chance you could add a pair command as well? I don't know the function signature for the Pair command. Cheers

**Comment by eggind** [comment]
Duplicate of previous request

**Comment by mortyobnoxious** [comment]
@lflfm Hi, sorry for writing this here. Since this is a small issue. I didn't wanted to open a new issue.

Is there a way to automatically unpair one specific device without being have to select it from powershell.

**Comment by lflfm** [comment]
> 
> 
> @lflfm Hi, sorry for writing this here. Since this is a small issue. I didn't wanted to open a new issue.
> 
> Is there a way to automatically unpair one specific device without being have to select it from powershell.

That's quite a good idea and not hard to implement (through command line arguments). I have created an enhancement request for that [here](https://github.com/lflfm/powerBTremover/issues/3)
